app/src/Pharmacie/InventaireBundle/Entity/Inventaire.php
<?php

namespace Pharmacie\InventaireBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Inventaire
 *
 * @ORM\Table(name="inventaire")
 * @ORM\Entity(repositoryClass="Pharmacie\InventaireBundle\Repository\InventaireRepository")
 */
class Inventaire
{
	
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateInventaire", type="datetimetz")
     */
    private $dateInventaire;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateDebut", type="date")
     */
    private $dateDebut;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateFin", type="date")
     */
    private $dateFin;
    
    /**
     * @var string
     *
     * @ORM\Column(name="rapport", type="string", length=255)
     */
    private $rapport;
	
    /**
     * @ORM\ManyToOne(targetEntity="Pharmacie\InventaireBundle\Entity\ModeleInventaire")
     * @ORM\JoinColumn(nullable=false)
     */
    private $modele;

    public function __construct(){
    	$this->dateInventaire = new \DateTime();
    }
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Inventaire
     */
    public function setDateInventaire($date)
    {
        $this->dateInventaire = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDateInventaire()
    {
        return $this->dateInventaire;
    }

    /**
     * Set dateDebut
     *
     * @param \DateTime $dateDebut
     *
     * @return Inventaire
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * Get dateDebut
     *
     * @return \DateTime
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }

    /**
     * Set dateFin
     *
     * @param \DateTime $dateFin
     *
     * @return Inventaire
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * Get dateFin
     *
     * @return \DateTime
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }

    /**
     * Set rapport
     *
     * @param string $rapport
     *
     * @return Inventaire
     */
    public function setRapport($rapport)
    {
        $this->rapport = $rapport;

        return $this;
    }

    /**
     * Get rapport
     *
     * @return string
     */
    public function getRapport()
    {
        return $this->rapport;
    }

    /**
     * Set modele
     *
     * @param \Pharmacie\InventaireBundle\Entity\ModeleInventaire $modele
     *
     * @return Inventaire
     */
    public function setModeleId(\Pharmacie\InventaireBundle\Entity\ModeleInventaire $modele)
    {
        $this->modele = $modele;

        return $this;
    }

    /**
     * Get modele
     *
     * @return \Pharmacie\InventaireBundle\Entity\ModeleInventaire
     */
    public function getModeleId()
    {
        return $this->modele;
    }


}

app/src/Pharmacie/InventaireBundle/Form/Type/InventaireType.php
<?php

namespace Pharmacie\InventaireBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class InventaireType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateInventaire', DateType::class, array(
                'widget' => 'choice',
                'years' => range(date('Y')+1, date('Y')+10)
                ))
            ->add('dateDebut', DateType::class, array(
                'widget' => 'choice',
                'years' => range(date('Y')+1, date('Y')+10)
                ))
            ->add('dateFin', DateType::class, array(
                'widget' => 'choice',
                'years' => range(date('Y')+1, date('Y')+10)
                ))
            //->add('rapport')
            ->add('modele_id', 'entity', array(
                    'class' => 'PharmacieInventaireBundle:ModeleInventaire',
                    'property' => 'libelle',
                ))
            ->add('Valider', 'submit')
            ->add('Annuler', 'submit');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Pharmacie\InventaireBundle\Entity\Inventaire'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'pharmacie_inventairebundle_inventaire';
    }


}

app/src/Pharmacie/InventaireBundle/Controller/InventaireController.php
<?php
namespace Pharmacie\InventaireBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
//use Symfony\Component\BrowserKit\Response;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Pharmacie\InventaireBundle\Entity\Inventaire;
use Pharmacie\InventaireBundle\Form\Type\InventaireType;
class InventaireController extends Controller
{
	public function indexAction()
	
	{		
		return $this->render('PharmacieInventaireBundle:Inventaire:index.html.twig');
	}
 
	
	public function pdfAction()
	{
		$html = $this->renderView('PharmacieInventaireBundle:Inventaire:index.html.twig');
		$filename = sprintf('test-%s.pdf', date('Y-m-d'));
	
		return new Response(
				$this->get('knp_snappy.pdf')->getOutputFromHtml($html),
				200,
				[
				'Content-Type'        => 'application/pdf',
				'Content-Disposition' => sprintf('attachment; filename="%s"', $filename),
				]
		);
	}


	public function faireInventaireAction(Request $request){
        $entite_inventaire = new Inventaire();
        $form_inventaire = new InventaireType();

        $form = $this->get('form.factory')->create($form_inventaire, $entite_inventaire);

        if ($form->handleRequest($request)->isValid()) 
        {
            if ($form->get('Valider')->isClicked())  
            {
                $em = $this->getDoctrine()->getManager();
                $em->persist($entite_inventaire);
                $em->flush();
                return $this->redirect($this->generateUrl('lister_inventaire'));
            }

        }

        if ($form->get('Annuler')->isClicked())  
        {
                 return $this->redirect($this->generateUrl('lister_inventaire'));
        }

        return $this->render('PharmacieInventaireBundle:Inventaire:faireinventaire.html.twig',array('formulaire' => $form->createView()));
    }
}

app/src/Pharmacie/InventaireBundle/Resources/views/Inventaire/faireinventaire.html.twig
{% extends "PharmacieInventaireBundle:Inventaire:listerinventaire.html.twig" %}
	 {% block table %}
	 <div class="">
        <center><h3 class="panel-heading alert-danger">Veuillez effectuer votre inventaire  </h3></center>

        {% set lol="2" %}

		{{ form_start(formulaire, {'attr': {'class': 'form-horizontal'}}) }}
		{{ form_errors(formulaire) }}
		

		<!-- debut du formulaire -->
		<div class="form-group">
		    {# Génération du label. #}
		    {{ form_label(formulaire.dateInventaire, "Date Inventaire ", {'label_attr': {'class': 'col-sm-4 control-label'}}) }}

		    {# Affichage des erreurs pour ce champ précis. #}
		    {{ form_errors(formulaire.dateInventaire) }}

		    <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(formulaire.dateInventaire, {'attr': {'class': 'form-control select_produit'}}) }}
		    </div>

		</div>


		<div class="form-group">
		    {# Génération du label. #}
		    {{ form_label(formulaire.dateDebut, "Date Debut", {'label_attr': {'class': 'col-sm-4 control-label'}}) }}

		    {# Affichage des erreurs pour ce champ précis. #}
		    {{ form_errors(formulaire.dateDebut) }}

		    <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(formulaire.dateDebut, {'attr': {'class': 'form-control'}}) }}
		    </div>
		</div>


		<div class="form-group">
		    {# Génération du label. #}
		    {{ form_label(formulaire.dateFin, "Date Fin", {'label_attr': {'class': 'col-sm-4 control-label'}}) }}

		    {# Affichage des erreurs pour ce champ précis. #}
		    {{ form_errors(formulaire.dateFin) }}

		    <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(formulaire.dateFin, {'attr': {'class': 'form-control'}}) }}
		    </div>
		</div>

		<div class="form-group">
		    {{ form_label(formulaire.modele_id, "Modele inventaire ", {'label_attr': {'class': 'col-sm-4 control-label'}}) }}
		    {{ form_errors(formulaire.modele_id) }}
		    <div class="col-sm-4">
		        {{ form_widget(formulaire.modele_id, {'attr': {'class': 'form-control'}}) }}
		    </div>
		</div>

        <center><span>{{ form_widget(formulaire.Valider, {'attr': {'class': 'btn btn-success'}}) }}</span>
         <span>{{ form_widget(formulaire.Annuler, {'label': 'Annuler', 'attr': {'class': 'btn btn-warning'}}) }}</span></center>

		{{ form_widget(formulaire) }}
		 {{ form_end(formulaire) }}	
		 </div><br><br>


	{%endblock%}

app/src/Pharmacie/InventaireBundle/Resources/views/Inventaire/index.html.twig
Hello World!

app/src/Pharmacie/InventaireBundle/Resources/views/Inventaire/listerinventaire.html.twig
{% extends "PharmacieAccueilBundle:Template:template1.html.twig" %}
{% block main %}
    <center><h5 class="alert alert-success">Listes des inventaires : Enregistrez votre inventaire </h5></center>
    <hr class="colorgraph">
    <div class="row">
       <div class="col-md-9" >
        {% block table %}
        <div class="table-responsive">
            <table id="mytable" class="table table-bordered ">
                <thead>
                    <th>Date inventaire</th>
                    <th>Date de debut</th>
                    <th>Date de fin</th>
                    <th>Modele</th>
                    
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for tag in inventaire %}
                     <tr>
                        <td>{{ tag.dateInventaire|date('d-M-Y') }}</td>
                        <td>{{ tag.dateDebut|date('d-M-Y') }}</td>
                        <td>{{ tag.dateFin|date('d-M-Y') }}</td>
                        <td>{{ tag.modeleId.libelle }}</td>
                       
                        <td><button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-list"></span>>PDF</button> 
                            <button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-list"></span>>Excel</button>
                        </td>
                    </tr>  
                     {% endfor %}                
                </tbody>
            </table>
        </div>
        {% endblock%}
        </div>
        <div class="col-md-3">
            <center><h5 class="panel-heading myheading">Actions à effectuer</h5></center>
            <hr class="colorgraph">
                <button class="btn-success btn-block sous-menu-item"><a href="#" class=""><span class="glyphicon glyphicon-tags"></span>  effectuer inventaire</a></button>
                <br>
                <button class="btn-success btn-block sous-menu-item"><a href="#" class=""><span class="glyphicon glyphicon-tags"></span>  modifier inventaire </a></button>
                 </br>
                <button type="button" class="btn-success btn-block sous-menu-item"><a href="#"><span class="glyphicon glyphicon-list"></span> supprimer inventaire </a></button>
        </div>
    </div>
    {% block reste %}
    <div class="row">
        <div class="col-md-3">
            <a href="{{ path('faire_inventaire')}}"><button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-plus"></span> effectuer inventaire </button></a>
        </div>
    </div>
    <br/><br/><br/>
    {% endblock %}

{% endblock%}